In [107]:
import pandas 
import numpy
import re # this module provides pattern matching operations among list of strings given
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
from nltk.stem import PorterStemmer

[nltk_data] Downloading package wordnet to C:\Users\Neema P
[nltk_data]     Eldho\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [108]:
data = pandas.read_csv("twitter_validation.csv",header = None)
df = pandas.DataFrame(data)
df

,0,1,2,3
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [109]:
df.columns = ["ID","PLATFORM","NATURE","COMMENT"]
df.head()

,ID,PLATFORM,NATURE,COMMENT
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...

In [110]:
df["COMMENT"] = df["COMMENT"].str.lower()
df["COMMENT"]

0      i mentioned on facebook that i was struggling ...
1      bbc news - amazon boss jeff bezos rejects clai...
2      @microsoft why do i pay for word when it funct...
3      csgo matchmaking is so full of closet hacking,...
4      now the president is slapping americans in the...
                             ...
995    ⭐️ toronto is the arts and culture capital of ...
996    this is actually a good move tot bring more vi...
997    today sucked so it’s time to drink wine n play...
998    bought a fraction of microsoft today. small wins.
999    johnson & johnson to stop selling talc baby po...
Name: COMMENT, Length: 1000, dtype: object

In [111]:
# re.sub(replacement , "", text)

def replace_text(text):

    text = re.sub(r'http\S+',"",text) # replace all urls starting with http or https with empty string
    # \S+  = Matches any non-whitespace character
    text = re.sub(r'[^a-z\s]',"",text)
    # \s   = Matches a single whitespace character 
    return text
df["COMMENT"] = df["COMMENT"].apply(replace_text)

df["COMMENT"]

0      i mentioned on facebook that i was struggling ...
1      bbc news  amazon boss jeff bezos rejects claim...
2      microsoft why do i pay for word when it functi...
3      csgo matchmaking is so full of closet hacking ...
4      now the president is slapping americans in the...
                             ...
995     toronto is the arts and culture capital of ca...
996    this is actually a good move tot bring more vi...
997    today sucked so its time to drink wine n play ...
998      bought a fraction of microsoft today small wins
999    johnson  johnson to stop selling talc baby pow...
Name: COMMENT, Length: 1000, dtype: object

In [112]:
# import word_tokenize

df["Tokens"] = df["COMMENT"].apply(word_tokenize)
df["Tokens"]

0      [i, mentioned, on, facebook, that, i, was, str...
1      [bbc, news, amazon, boss, jeff, bezos, rejects...
2      [microsoft, why, do, i, pay, for, word, when, ...
3      [csgo, matchmaking, is, so, full, of, closet, ...
4      [now, the, president, is, slapping, americans,...
                             ...
995    [toronto, is, the, arts, and, culture, capital...
996    [this, is, actually, a, good, move, tot, bring...
997    [today, sucked, so, its, time, to, drink, wine...
998    [bought, a, fraction, of, microsoft, today, sm...
999    [johnson, johnson, to, stop, selling, talc, ba...
Name: Tokens, Length: 1000, dtype: object

In [113]:
# remove stop words

stop_words = set(stopwords.words("english"))
df["Tokens"] = df["Tokens"].apply(lambda a : [i for i in a if i not in stop_words])
df["Tokens"]

0      [mentioned, facebook, struggling, motivation, ...
1      [bbc, news, amazon, boss, jeff, bezos, rejects...
2      [microsoft, pay, word, functions, poorly, sams...
3      [csgo, matchmaking, full, closet, hacking, tru...
4      [president, slapping, americans, face, really,...
                             ...
995    [toronto, arts, culture, capital, canada, wond...
996    [actually, good, move, tot, bring, viewers, on...
997    [today, sucked, time, drink, wine, n, play, bo...
998    [bought, fraction, microsoft, today, small, wins]
999    [johnson, johnson, stop, selling, talc, baby, ...
Name: Tokens, Length: 1000, dtype: object

In [114]:
# lemmatization

lemmatizer = WordNetLemmatizer() # method called lematize used for stemming each tokens in each row
# Lemmatize as verbs
df["Tokens_verb"] = df["Tokens"].apply(lambda a: [lemmatizer.lemmatize(i, pos="v") for i in a])

# Lemmatize as nouns
df["Tokens_noun"] = df["Tokens"].apply(lambda a: [lemmatizer.lemmatize(i, pos="n") for i in a])

# Lemmatize as adjectives
df["Tokens_adj"] = df["Tokens"].apply(lambda a: [lemmatizer.lemmatize(i, pos="a") for i in a])

# Lemmatize as adverbs
df["Tokens_adv"] = df["Tokens"].apply(lambda a: [lemmatizer.lemmatize(i, pos="r") for i in a])

df["Tokens"]

0      [mentioned, facebook, struggling, motivation, ...
1      [bbc, news, amazon, boss, jeff, bezos, rejects...
2      [microsoft, pay, word, functions, poorly, sams...
3      [csgo, matchmaking, full, closet, hacking, tru...
4      [president, slapping, americans, face, really,...
                             ...
995    [toronto, arts, culture, capital, canada, wond...
996    [actually, good, move, tot, bring, viewers, on...
997    [today, sucked, time, drink, wine, n, play, bo...
998    [bought, fraction, microsoft, today, small, wins]
999    [johnson, johnson, stop, selling, talc, baby, ...
Name: Tokens, Length: 1000, dtype: object

In [115]:
# stemming 

obj = PorterStemmer()
df["Tokens"] = df["Tokens"].apply(lambda a : [obj.stem(i) for i in a])
df["Tokens"]

0      [mention, facebook, struggl, motiv, go, run, d...
1      [bbc, news, amazon, boss, jeff, bezo, reject, ...
2      [microsoft, pay, word, function, poorli, samsu...
3      [csgo, matchmak, full, closet, hack, truli, aw...
4      [presid, slap, american, face, realli, commit,...
                             ...
995    [toronto, art, cultur, capit, canada, wonder, ...
996    [actual, good, move, tot, bring, viewer, one, ...
997    [today, suck, time, drink, wine, n, play, bord...
998     [bought, fraction, microsoft, today, small, win]
999    [johnson, johnson, stop, sell, talc, babi, pow...
Name: Tokens, Length: 1000, dtype: object